dist: trusty
sudo: false
language: php

php:
  - 7.2
  - 7.3
  - nightly

before_install:
  - composer self-update

install:
  - travis_retry composer install --prefer-dist

script:
  - ./vendor/bin/phpunit -v

jobs:
  include:
    - stage: Code Quality
      env: ANALYSIS=phpstan
      php: 7.2
      script: vendor/bin/phpstan analyse

    - stage: Code Quality
      env: ANALYSIS=CODING_STANDARDS
      php: 7.2
      script: ./vendor/bin/phpcs

  allow_failures:
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache
